review solid and clean code
Shafagh-Sepehr/Full-Text-Search pull request #1
Opened 2024-10-02 05:01 UTC by Shafagh-Sepehr

2024-10-03 17:33 UTC, navidnasyry requested changes
Read more about Design Patterns :

Singleton
Factory
Strategy
and ...

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/Program.cs
> +        var invertedIndex = new InvertedIndexDictionary("/home/shafagh/Desktop/EnglishData", ["will",]);
آدرس رو هارد کد بذاریم؟‌ راه بهتر چی هست؟ چرا؟

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/Program.cs
> +        Console.Write("Search: ");
کلا برا خروجی ها چطوره یه کلاس داشته باشیم؟

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/Program.cs
> +        string? query = Console.ReadLine();
و همچنین ورودی گرفتن‌ها؟

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/Program.cs
> +        if (string.IsNullOrWhiteSpace(query)) return;
خطا مشخص نیست 
write new exception

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/Program.cs
> +        foreach (string doc in result)
{
}

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/Program.cs
> +        foreach (string doc in result)
use Implicitly type. why?

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/Program.cs
> +            Console.WriteLine(doc);
use class and interface

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/InvertedIndexDictionary.cs
> +        invertedIndexDictionaryBuilder ??= new InvertedIndexDictionaryBuilder(stringToWordsProcessor, englishPorter2Stemmer);
این کلاس به چه کلاس‌های دیگه وابستس؟ این خوبه؟

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/InvertedIndexDictionaryBuilder.cs
> +        string[] files = Directory.GetFiles(filepath);
var

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/QuerySearcher.cs
> +
use blocks

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/QuerySearcher.cs
> +
هر کدوم از این کارا میتونن یه سرویس جدا بشن

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/QuerySearcher.cs
> +internal class QuerySearcher(IPorter2Stemmer? stemmer = null) : IQuerySearcher
این کلاس خیلی طولانیه که داره همه کاری میکنه:)

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/QuerySearcher.cs
> +
یه سرویس جدا که اینا رو ارائه بده

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/QuerySearcher.cs
> +    }
ایضا

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/QuerySearcher.cs
> +    }
..

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/QuerySearcher.cs
> +    }
another class

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/QuerySearcher.cs
> +    }
...

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/QuerySearcher.cs
> +}
...

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/StringToWordsProcessor.cs
> +    ];
راه بهتر بجای هارد کد کردن

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/StringToWordsProcessor.cs
> +            .Distinct();
tooooo long:(

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/StringToWordsProcessor.cs
> +            .Distinct();
extract method and variable

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/StringToWordsProcessor.cs
> +    [GeneratedRegex(@"^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$")]
خوانا نیست...چرا نیازه؟

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/StringToWordsProcessor.cs
> +        value = value.Trim(":.,<>?/\\\"\t'`~!@#$%^&*()_+=-*;\t |".ToCharArray()); //trim noise around probably important words
کد اونقدر باید خوانا باشه که نیاز به کامنت نداشته باشه:)
حذف کامنت و خوانا تر کردن با متغیر و متد و کلاس

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/StringToWordsProcessor.cs
> +
"""

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/InvertedIndexDictionaryBuilder.cs
> +            foreach (string word in words)
{}

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/InvertedIndexDictionaryBuilder.cs
> +            foreach (string word in words)
extract method

2024-10-03 17:33 UTC, navidnasyry commented on FullTextSearch/QuerySearcher.cs
> +    public IEnumerable<string> Search(string query, Dictionary<string, List<string>> invertedIndex)
S in Solid

2024-10-03 17:38 UTC, navidnasyry reviewed
و راستی...
پوشه بندی هم میتونه بهتر باشه بر اساس کار‌هایی که انجام میشه
میتونی 
Clean Architecture و MVC
رو هم بخونی

2024-10-06 18:59 UTC, Shafagh-Sepehr commented on FullTextSearch/Program.cs
> +        var invertedIndex = new InvertedIndexDictionary("/home/shafagh/Desktop/EnglishData", ["will",]);
یه فایل appsettings.json درست کردم گذاشتم اونجا.
تا هم اگه خواست عوض بشه جاش معلوم باشه هم فرضا اگه برنامه بزرگتر شد یه جا برای اینطور مقادیر داشته باشیم

2024-10-09 09:37 UTC, closed without merging